name: iOS App Build

on:
  push:
    branches: [ main ]
    paths:
      - 'EasyKeyboard/**'
      - '.github/workflows/ios-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'EasyKeyboard/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Cache Xcode DerivedData
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-

    - name: Build iOS App
      run: |
        cd EasyKeyboard
        xcodebuild \
          -project EasyKeyboard.xcodeproj \
          -scheme EasyKeyboard \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          clean build

    - name: Archive Build
      run: |
        cd EasyKeyboard
        xcodebuild \
          -project EasyKeyboard.xcodeproj \
          -scheme EasyKeyboard \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath build/EasyKeyboard.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          archive

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: |
          EasyKeyboard/build/
          EasyKeyboard/DerivedData/

  test:
    runs-on: macos-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Run Unit Tests
      run: |
        cd EasyKeyboard
        xcodebuild test \
          -project EasyKeyboard.xcodeproj \
          -scheme EasyKeyboard \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO